apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: spring
imagePullSecrets:
  - name: regcred

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillpillweb-spring
  namespace: spring
  labels:
    app: spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: <account>/<repo>:skillpillweb-spring
        imagePullPolicy: Always
        ports:
        - containerPort: 3738
          name: spring-port
        livenessProbe:
          httpGet:
            path: /health/health
            port: spring-port
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 2
          failureThreshold: 2
        volumeMounts:
          - name: application-properties
            mountPath: "/app/application.properties"
            subPath: application.properties
            readOnly: true
          - name: spring-cert
            mountPath: "/app/cert/skillpillweb-spring-service.spring.p12"
            subPath: skillpillweb-spring-service.spring.p12
            readOnly: true
      volumes:
      - name: application-properties
        secret:
          secretName: spring-application-properties
          items:
          - key: application.properties
            path: application.properties
      - name: spring-cert
        secret:
          secretName: spring-cert
          items:
          - key: skillpillweb-spring-service.spring.p12
            path: skillpillweb-spring-service.spring.p12
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: skillpillweb-spring-service
  namespace: spring
spec:
  type: ClusterIP
  selector:
    app: spring
  ports:
    - name: https-spring-service-port
      protocol: TCP
      port: 3738
      targetPort: spring-port
